# fly.toml app configuration file for UBAS Financial Trust API
# Docs: https://fly.io/docs/reference/configuration/

app = "ubasfintrust-api"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "30s"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  API_VERSION = "v1"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 100
    hard_limit = 200

  [[http_service.checks]]
    # Fast liveness
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "2s"

  [[http_service.checks]]
    # Readiness (DB ready)
    grace_period = "20s"
    interval = "20s"
    method = "GET"
    path = "/health/readiness"
    protocol = "http"
    timeout = "3s"

[deploy]
  # Run DB migrations during deploy
  release_command = "npm run migrate:prod"
