
name = "ubasfintrust-api"
main = "src/worker.ts"
compatibility_date = "2025-08-16"
type = "module"

[[d1_databases]]
binding = "DB"
database_name = "app-db"
database_id = "508c304a-fa6b-4ecc-be04-fa70418bd377"
