name = "ubasfintrust"
main = "src/worker.ts"
compatibility_date = "2025-08-16"

[[kv_namespaces]]
binding = "APP_KV"
id = "acb18fc63b9e4e42a6124b11c5c0e1f7"

[vars]
NODE_ENV = "production"
JWT_AUD = "ubas"
RATE_LIMIT_WINDOW_SEC = "60"
RATE_LIMIT_MAX = "60"
# Secrets (SET VIA CLI, DO NOT COMMIT):
# wrangler secret put JWT_SECRET
# wrangler secret put DATABASE_URL
