name: Deploy Frontend (Pages) and Worker

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps and build
        run: |
          npm ci
          npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Install wrangler
        run: npm i -g wrangler

      - name: Create Pages project if missing
        run: |
          set -e
          if ! wrangler pages project list --json | jq -e --arg NAME "${{ secrets.CLOUDFLARE_PAGES_PROJECT }}" '.[] | select(.name == $NAME)' >/dev/null; then
            wrangler pages project create "${{ secrets.CLOUDFLARE_PAGES_PROJECT }}" --production-branch=main --compatibility-date=$(date +%Y-%m-%d)
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Publish to Cloudflare Pages (wrangler)
        run: |
          wrangler pages deploy dist --project-name="${{ secrets.CLOUDFLARE_PAGES_PROJECT }}" --branch=main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      

      - name: Publish Worker
        working-directory: edge-worker
        run: |
          npm ci
          if [ -n "${{ secrets.JWT_SECRET }}" ]; then echo "${{ secrets.JWT_SECRET }}" | wrangler secret put JWT_SECRET; fi
          if [ -n "${{ secrets.DATABASE_URL }}" ]; then echo "${{ secrets.DATABASE_URL }}" | wrangler secret put DATABASE_URL; fi
          wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
